{ // Status Ailments [AilmentsOBJ]
AilmentsOBJ = [
 ["","Poison"]
,["","Stun"]
,["","Freeze"]
,["","Curse"]
,["�","Blind"]
,["","Sleep"]
,["��","Silence"]
,["","Chaos"]
,["�","Bleeding"]
,["","Stone"]
,["","Weapon Break"]
,["","Armor Break"]
,["","Deep Sleep"]
,["","Venom Impress"]
,["","Marsh of Abyss"]
,["","Burning"]
,["","Cristallization"]
,["","Gloomy Day"]
,["","Dark Claw"]
];
}