{ // WeaponTypes [WeaponName]
WeaponName = [
[" }Kb","Unarmed"]
,["íwcR","Dagger"]
,["GrKbcR","Sword"]
,["!NKbcR","Two-handed Sword"]
,["GrKbÍi","Spear"]
,["!NKbÍi","Two-handed Spear"]
,["GrKb§e","Axe"]
,["!NKb§e","Two-handed Axe"]
,["hV","Mace"]
,["Vg","Rod"]
,["_","Bow"]
,["«0¿0ü0ë0","Katar"]
,[",g","Book"]
,["Ê0Ã0¯0ë0","Knuckle"]
,["}ihV","Instrument"]
,["­—","Whip"]
,["¨˜T›KbÏˆcR","Huuma Shuriken"]
,["Ï0ó0É0¬0ó0","Handgun"]
,["é0¤0Õ0ë0","Rifle"]
,["·0ç0Ã0È0¬0ó0","Shotgun"]
,["¬0È0ê0ó0°0¬0ó0","Gatling Gun"]
,["°0ì0Í0ü0É0¬0ó0","Grenade Launcher"]
];
}
